# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: disconnecter
custom: https://buymeacoffee.com/badlinks
custom: https://t.me/badlinkschannel
